name: Simple Shared Action
author: pakwai
inputs:
  with-value:
    description: GitHub workflow token
    required: false
runs:
  using: "composite"
  steps:
    - name: With Value
      if: ${{ inputs.with-value != 0 }}
      run: echo "shout=${{ inputs.with-value }}" >> $GITHUB_ENV
      shell: bash
    - name: With No Value
      if: ${{ inputs.with-value == 0 }}
      run: echo "shout=No value" >> $GITHUB_ENV
      shell: bash
    - name: Convert base64
      run: echo "${{ env.shout }}" | base64
      shell: bash

