name: If-else test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run composite
      # uses: sr-pakwai/zap-pipeline-test/zap-composite@master
      uses: ./simple-composite
      id: composite-scan
      env:
        MY_VALUE: hihi
      with:
        with-value: ${{ env.MY_VALUE }}
