name: Centralize Zap Scan
on: push
# The trigger to which the workflow will run 
jobs:
  Zap_scan:
    strategy:
      matrix:
        urlTitle:
          - Zaproxy
          - Google
        include:
          - urlTitle: Zaproxy
            endpoint: 'https://www.zaproxy.org'
          - urlTitle: Google
            endpoint: 'https://www.google.com'
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan - (${{ matrix.urlTitle }})
        uses: zaproxy/action-baseline@master
        # https://www.zaproxy.org/docs/desktop/start/features/authentication/
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.endpoint }}
          allow_issue_writing: false
          # https://www.zaproxy.org/docs/docker/baseline-scan/
          cmd_options: ''
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: zap_${{ matrix.urlTitle }}
          path: ${{ github.workspace }}
      - name: Upload folder to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: ${{ github.workspace }}
          name: zap_${{ matrix.urlTitle }}
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          folder: ${{ secrets.DRIVE_FOLDERID }}