name: Matrix Strategy Sample
on: push
# The trigger to which the workflow will run 
jobs:
  example_matrix:
    strategy:
      matrix:
        endpoint:
          - 'https://www.zaproxy.org'
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ZAP Baseline Scan - (${{ matrix.endpoint }})
        uses: zaproxy/action-baseline@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.endpoint }}
          allow_issue_writing: false
          # https://www.zaproxy.org/docs/docker/baseline-scan/
          cmd_options: '-d'
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: pentest-report-${{ matrix.endpoint }}
          path: /home/runner/work/zap-pipeline-test/zap-pipeline-test/