name: Centralize Zap Scan
on: push
# The trigger to which the workflow will run 
jobs:
  Zap_scan:
    strategy:
      matrix:
        urlTitle:
          - Zaproxy
          # - Google
        include:
          - urlTitle: Zaproxy
            endpoint: 'https://www.zaproxy.org'
          # - urlTitle: Google
          #   endpoint: 'https://www.google.com'
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: ZAP Baseline Scan - (${{ matrix.urlTitle }})
        uses: zaproxy/action-baseline@master
        # https://www.zaproxy.org/docs/desktop/start/features/authentication/
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.endpoint }}
          allow_issue_writing: false
          # https://www.zaproxy.org/docs/docker/baseline-scan/
          cmd_options: ''
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: zap_${{ matrix.urlTitle }}
          path: ${{ github.workspace }}
      - name: Send file
        id: send
        uses: hankei6km/gdrive-act-send@v0.5.1
        with:
          parent_id: ${{ secrets.DRIVE_FOLDERID }}
          dest_file_name: zap_${{ github.event.repository.name }}_${{ matrix.urlTitle }}
          src_file_name: zap_${{ matrix.urlTitle }}
