name: Matrix Strategy Sample
on: push
# The trigger to which the workflow will run 
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        endpoint:
          - 'https://www.zaproxy.org'
          - 'https://www.google.com'
        include:
          - urlTitle: Zaproxy
            endpoint: 'https://www.zaproxy.org'
          - urlTitle: Google
            endpoint: 'https://www.google.com'
    runs-on: ${{ matrix.os }}
    steps:
      - name: ZAP Baseline Scan - (${{ matrix.urlTitle }})
        uses: zaproxy/action-baseline@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.endpoint }}
          allow_issue_writing: false
          # https://www.zaproxy.org/docs/docker/baseline-scan/
          cmd_options: ''
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: report-${{ matrix.urlTitle }}
          path: ${{ github.workspace }}