name: Matrix Strategy Sample
on: push
# The trigger to which the workflow will run 
jobs:
  example_matrix:
    strategy:
      matrix:
        endpoint:
          - 'https://www.zaproxy.org'
          - 'https://www.google.com'
          - 'https://www.github.com'
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ZAP Baseline Scan - (${{ matrix.endpoint }})
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ matrix.endpoint }}