name: Output Test
on: [workflow_dispatch]
jobs:
  Start-App:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "name=date::$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Test Output
        id: test
        run: echo ${{ steps.date.outputs.date }}
